version: '2.1'

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    networks:
      - media
    environment:
      - PLEX_CLAIM="${PLEX_TOKEN}"
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/radarr/movies:/data/movies
      - ./media/sonarr/series:/data/tvshows
      - ./media/plex/config/:/config
      - /tmp/transcode/:/transcode
    ports:
      - 32400:32400
    depends_on:
      - transmission
      - sonarr
      - radarr

  plexpy:
    image: linuxserver/plexpy:latest
    container_name: plexpy
    networks:
      - media
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./media/plexpy:/config
      - ./media/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 8181:8181
    depends_on:
      - plex

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    networks:
      - media
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/transmission/config/:/config
      - ./media/transmission/downloads/:/downloads
    ports:
      - 9091:9091

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/sonarr/series:/tv
      - ./media/sonarr/config:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8989:8989
    depends_on:
      - transmission

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/radarr/movies:/movies
      - ./media/radarr/config:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    depends_on:
      - transmission

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - media
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - /media/lidarr/config:/config
      - /media/lidarr/music:/music
      - /media/transmission/downloads/:/downloads
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
    depends_on:
      - transmission

  # Proxy to a bunch of public trackers
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    networks:
      - media
    volumes:
      - ./media/jackett/config/:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 9117:9117

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: always
    networks:
      - media
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/ombi/config:/config
    ports:
      - 3579:3579

networks:
  media:
    external: false